"""Add Workitem model for branch

Revision ID: 344866ce3153
Revises: 
Create Date: 2025-01-19 16:14:03.112679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344866ce3153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_item')
    # ### end Alembic commands ###
