"""Add code and sqm to branch default value

Revision ID: 7a3ff8061c6b
Revises: 99f554840030
Create Date: 2025-01-19 18:11:01.033834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3ff8061c6b'
down_revision = '99f554840030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('work_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    # ### end Alembic commands ###
